# Brief description of what this image intends to do
# How the image can be used etc


# Specify the image name and tag
# Which repo is being used

FROM <IMAGE_NAME:TAG>


# Mention the work dir , avoid doing cd

WORKDIR <>


# Describe the file being added and why it is required

ADD <>


# Provide brief description what the RUN command is expected to achieve. Explain each command separated by &&
# Provide description for each RUN command being used
# Adding test comment #######################################

RUN <>


# Describe the command/script used in entrypoint

CMD <>
